name: Lint and Typecheck

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: ["master", "dev"]

jobs:
  eslint:
    name: Run eslint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup/Retrieve npm build chache
        uses: bahmutov/npm-install@v1

      - name: Run linter
        run: npm i && npm run lint
  typecheck:
    name: Run typecheck
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup/Retrieve npm build chache
        uses: bahmutov/npm-install@v1

      - name: Run typecheck
        run: npm i && npm run check
